welcome_text = 'Hi!\n\nWelcome to  Optical Character Recognizer Bot 🔍.\n\nJust send a clear image to me and I will recognize the text in the image and send it as a message💬!'
reply_to_text_message = 'Hey, I\'m not designed to reply to text messages 😕\nHit /start and read the instructions!'
no_text_found = 'It\'s time to get my eye 👀 tested\nI\'m not able to read any text in this image 😔\nTrust me, I even tried with my 👓 on!'
processing_your_image = 'Hold back tight.\nWe are decoding your image 👨‍💻️'
contact_me = 'For any queries reach out to @dronefill'
